# The name is purely descriptive and is used for display purposes in the GitHub Actions UI to help you and other contributors understand what the workflow does
name: Label issues

# "on" defines the trigger for our workflow, here it is the pull_request(either opening the pr or editing the pr). So whenver these trigger happen, the workflow will be executed
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  # This Job is used to add any label which you want to add on the issues whenver they are created
  label_issues: # Name of the Job
    runs-on: ubuntu-latest # This specifies that job should run on the latest version of the Ubuntu runner, which is a VM environment provided by GitHub Actions
    permissions:
      issues: write

    steps:
      - uses: actions/github-script@v6
        with:
          # The issue_number, owner, and repo values are automatically set using the context object. You do not need to change these.
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number, 
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["good first issue", "hacktoberfest"]
            })
